apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
      app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
        app: node-app
  template:
    metadata:
      labels:
          app: node-app
    spec:
      containers:
      - name: node-app
        image: edmirh/bacholer-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: <DB_PASSWORD>
        - name: DB_HOST
          value: <DB_HOST>
        - name: DB_DIALECT
          value: "postgres"
        - name: DB_TEST
          value: "bacholer_database"
        - name: NODE_ENV
          value: "test"
        - name: PORT
          value: "8080"
      imagePullSecrets:
      - name: regcred